accounts/urls.py
from django.urls import path

from accounts.views import login_view, register, logout_view, update_profile, upload_profile_picture
from django.conf import settings
from django.conf.urls.static import static

app_name = "accounts"

urlpatterns = [
    path('profile/edit', update_profile, name='profile_edit'),
    path('login', login_view, name='login'),
    path('register', register, name='register'),
    path('logout', logout_view, name='logout'),
    path('profile/upload', upload_profile_picture, name='profile_picture_upload'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path

from app.views import index, MatchesListView, MemberDetailView, like, dislike, LikedMeListView, WhomILikedListView, \
    MatchesFilterListView
from django.contrib.auth.decorators import login_required

app_name = "app"

urlpatterns = [
    path('', index),
    path('matches', login_required(MatchesListView.as_view(), login_url='/login'), name='matches'),
    path('members/<int:pk>', MemberDetailView.as_view(), name='member_detail'),
    path('like/<int:id>', like, name='like'),
    path('dislike/<int:id>', dislike, name='dislike'),
    path('liked-me', login_required(LikedMeListView.as_view(), login_url='/login'), name='liked_me'),
    path('whom-i-liked', login_required(WhomILikedListView.as_view(), login_url='/login'), name='whom_i_liked'),
    path('filter', MatchesFilterListView.as_view(), name='filter'),
]

datingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('app.urls', namespace='app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/app.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Find Partner</title>

    {% load staticfiles %}

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-dark bg-danger">
        <div class="container">
            <a class="navbar-brand" href="/">
                Find Partner
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app:matches' %}">All Matches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app:whom_i_liked' %}">Whom I liked</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app:liked_me' %}">Who liked me</a>
                        </li>
                    </ul>
                {% endif %}

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ request.user.username|capfirst }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                                <a class="dropdown-item" href="{% url 'accounts:profile_edit' %}">
                                    <i class="fa fa-user"></i> Edit Profile
                                </a>

                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                                    <i class="fa fa-sign-out"></i> Logout
                                </a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        {% block content %}
        {% endblock %}
    </main>
</div>

<!-- Scripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>

<script>
    $(document).on('click', '[data-toggle="lightbox"]', function (event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    });
</script>
</body>
</html>