app/urls.py
from django.urls import path

from app.views import index, MatchesListView, MemberDetailView, like, dislike, LikedMeListView, WhomILikedListView, \
    MatchesFilterListView
from django.contrib.auth.decorators import login_required

app_name = "app"

urlpatterns = [
    path('', index),
    path('matches', login_required(MatchesListView.as_view(), login_url='/login'), name='matches'),
    path('members/<int:pk>', MemberDetailView.as_view(), name='member_detail'),
    path('like/<int:id>', like, name='like'),
    path('dislike/<int:id>', dislike, name='dislike'),
    path('liked-me', login_required(LikedMeListView.as_view(), login_url='/login'), name='liked_me'),
    path('whom-i-liked', login_required(WhomILikedListView.as_view(), login_url='/login'), name='whom_i_liked'),
    path('filter', MatchesFilterListView.as_view(), name='filter'),
]

datingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('app.urls', namespace='app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/filtermatches.html
{% extends 'layouts/app.html' %}

{% block content %}
    {% load static %}
    {% load is_liked_by_me %}

    <div class="container mt-3">
        <div class="text-center mt-3">
            <h2>Your matches - {{ matches.count }} found</h2>
        </div>

        <form class="form-inline" action="{% url 'app:filter' %}" method="get">
            <div class="form-group">
                <label for="minAge">Age From</label>
                <input type="number" class="form-control ml-1" style="width: 70px" value="18" id="minAge" name="minAge">
            </div>

            <div class="form-group px-2">
                <label for="maxAge">Age To</label>
                <input type="number" class="form-control ml-1" style="width: 70px" value="99" id="maxAge" name="maxAge">
            </div>

            <div class="form-group px-2">
                <label for="gender">Show: </label>
                <select class="form-control ml-1" style="width: 130px" id="gender" name="gender">
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                </select>
            </div>
            <button type="submit" class="btn btn-success" style="margin-left:10px">Apply Filters</button>
            <button type="reset" class="btn btn-info" style="margin-left:10px">
                Reset Filter
            </button>
        </form>
        <br>

        <div class="row">
            {% for match in matches %}

                <div class="col-md-3">
                    <div class="card mb-4">
                        <div class="card-img-wrapper">
                            <img class="card-img-top img-thumbnail" src="{% static "images/user.png" %}" alt="">
                            <ul class="list-inline member-icons animate text-center">
                                <li class="list-inline-item">
                                    <a href="{% url 'app:member_detail' match.id %}" class="btn btn-primary"
                                       title="Show profile">
                                        <i style="color: #fff;" class="fa fa-user"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    {% is_liked_by_me match request.user as is_liked %}
                                    {% if is_liked %}
                                        <form action="{% url 'app:dislike' match.id %}" method="post">
                                            {% csrf_token %}
                                            <button class="btn btn-primary" title="Dislike it">
                                                <i style="color: #ff3f3e" class="fa fa-heart"></i>
                                            </button>
                                        </form>
                                    {% else %}
                                        <form action="{% url 'app:like' match.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-primary" title="Like it">
                                                <i class="fa fa-heart"></i>
                                            </button>
                                        </form>
                                    {% endif %}
                                </li>
                                <li class="list-inline-item">
                                    <a href="" class="btn btn-primary"
                                       title="Send Message">
                                        <i style="color: #ffffff;" class="fa fa-envelope"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body p-1">
                            <h6 class="card-title text-center mb-1"><i class="fa fa-user"></i>
                                {{ match.username }}
                            </h6>
                            <p class="card-text text-muted text-center">Age:
                                <small>{{ match.age }}</small>
                            </p>
                            <p class="card-text text-muted text-center">Dhaka</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="row justify-content-center">
            {% if is_paginated %}
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <a class="page-link" href="#">
                                        {{ i }} <span class="sr-only">(current)</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="{{ request.get_full_path }}&page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/home.html
{% extends 'layouts/app.html' %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="jumbotron" style="font-size: 20px">
                    Find Your Partner
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/likedme.html
{% extends 'layouts/app.html' %}

{% block content %}
    {% load static %}
    {% load is_liked_by_me %}

    <div class="text-center mt-3">
        <h2>{{ likes.count }} people liked you</h2>
    </div>

    <div class="container mt-3">

        <div class="row">
            {% for like in likes %}
                <div class="col-sm-6 col-md-4 col-lg-4 col-xl-2">
                    <div class="card mb-4">
                        <div class="card-img-wrapper">
                            <img class="card-img-top img-thumbnail" src="{% static 'images/user.png' %}" alt="">
                            <ul class="list-inline member-icons animate text-center">
                                <li class="list-inline-item">
                                    <a href="{% url 'app:member_detail' like.user.id %}" class="btn btn-primary"
                                       title="Show profile">
                                        <i style="color: #fff;" class="fa fa-user"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <button class="btn btn-primary" title="Send Message">
                                        <i class="fa fa-envelope"></i>
                                    </button>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body p-1">
                            <h6 class="card-title text-center mb-1"><i class="fa fa-user"></i>
                                {{ like.user.username }}
                            </h6>
                            <p class="card-text text-muted text-center">Age:
                                <small>{{ like.user.age }}</small>
                            </p>
                            <p class="card-text text-muted text-center">Dhaka</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="d-flex justify-content-center">

    </div>

{% endblock %}

templates/matches.html
{% extends 'layouts/app.html' %}

{% block content %}
    {% load static %}
    {% load is_liked_by_me %}

    <div class="container mt-3">
        <div class="text-center mt-3">
            <h2>Your matches - {{ matches.count }} found</h2>
        </div>

        <form class="form-inline" action="{% url 'app:filter' %}" method="get">
            <div class="form-group">
                <label for="minAge">Age From</label>
                <input type="number" class="form-control ml-1" style="width: 70px" value="18" id="minAge" name="minAge">
            </div>

            <div class="form-group px-2">
                <label for="maxAge">Age To</label>
                <input type="number" class="form-control ml-1" style="width: 70px" value="99" id="maxAge" name="maxAge">
            </div>

            <div class="form-group px-2">
                <label for="gender">Show: </label>
                <select class="form-control ml-1" style="width: 130px" id="gender" name="gender">
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                </select>
            </div>
            <button type="submit" class="btn btn-success" style="margin-left:10px">Apply Filters</button>
            <button type="reset" class="btn btn-info" style="margin-left:10px">
                Reset Filter
            </button>
        </form>
        <br>

        <div class="row">
            {% for match in matches %}

                <div class="col-md-3">
                    <div class="card mb-4">
                        <div class="card-img-wrapper">
                            <img class="card-img-top img-thumbnail" src="{% static "images/user.png" %}" alt="">
                            <ul class="list-inline member-icons animate text-center">
                                <li class="list-inline-item">
                                    <a href="{% url 'app:member_detail' match.id %}" class="btn btn-primary"
                                       title="Show profile">
                                        <i style="color: #fff;" class="fa fa-user"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    {% is_liked_by_me match request.user as is_liked %}
                                    {% if is_liked %}
                                        <form action="{% url 'app:dislike' match.id %}" method="post">
                                            {% csrf_token %}
                                            <button class="btn btn-primary" title="Dislike it">
                                                <i style="color: #ff3f3e" class="fa fa-heart"></i>
                                            </button>
                                        </form>
                                    {% else %}
                                        <form action="{% url 'app:like' match.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-primary" title="Like it">
                                                <i class="fa fa-heart"></i>
                                            </button>
                                        </form>
                                    {% endif %}
                                </li>
                                <li class="list-inline-item">
                                    <a href="" class="btn btn-primary"
                                       title="Send Message">
                                        <i style="color: #ffffff;" class="fa fa-envelope"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body p-1">
                            <h6 class="card-title text-center mb-1"><i class="fa fa-user"></i>
                                {{ match.username }}
                            </h6>
                            <p class="card-text text-muted text-center">Age:
                                <small>{{ match.age }}</small>
                            </p>
                            <p class="card-text text-muted text-center">Dhaka</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="row justify-content-center">
            {% if is_paginated %}
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <a class="page-link" href="#">
                                        {{ i }} <span class="sr-only">(current)</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/memberdetail.html
{% extends 'layouts/app.html' %}

{% block content %}

    {% load static %}
    {% load is_liked_by_me %}

    <div class="container mt-4">
        <div class="row">
            <h1>{{ user.username }}'s Profile</h1>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="card">

                    <img class="card-img-top img-thumbnail" src="{% static 'images/user.png' %}" alt="">

                    <div class="card-body">
                        <div>
                            <strong>Location:</strong>
                            {% if user.city or user.country %}
                                <p>{{ user.city }}, {{ user.country }}</p>
                            {% else %}
                                Not Available
                            {% endif %}
                        </div>
                        <div>
                            <strong>Age:</strong>
                            <p>{{ user.age }}</p>
                        </div>
                        <div>
                            <strong>Last Active:</strong>
                            <p>{{ user.updated_at }}</p>
                        </div>
                        <div>
                            <strong>Member Since:</strong>
                            <p>{{ user.created_at }}</p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="btn-group d-flex">
                            {% is_liked_by_me user request.user as is_liked %}
                            {% if is_liked %}
                                <form action="{% url 'app:dislike' user.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" style="color: #ffffff" class="btn btn-danger w-100">
                                        Liked
                                    </button>
                                </form>
                            {% else %}
                                <form action="{% url 'app:like' user.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" style="color: #ffffff" class="btn btn-primary w-100">
                                        Like
                                    </button>
                                </form>
                            {% endif %}
                            <button class="btn btn-success w-100">Message</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="tab-panel">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#about">Abut</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#interests">Interests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#photos">Photos</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div id="about" class="container tab-pane active"><br>
                            <p>{{ user.about }}</p>
                        </div>
                        <div id="interests" class="container tab-pane fade"><br>
                            <p>{{ user.interests }}</p>
                        </div>
                        <div id="photos" class="container tab-pane fade"><br>
                            <div class="row">
                                {#                                @forelse($user->photos as $photo)#}
                                {#                                <a href="{{ asset($photo->path)}}" data-toggle="lightbox" data-gallery="example-gallery"#}
                                {#                                   class="col-sm-4">#}
                                {#                                    <img src="{{ asset($photo->path)}}" class="img-fluid">#}
                                {#                                </a>#}
                                {#                                @empty#}
                                {#                                <h2>No Photos uploaded yet!</h2>#}
                                {#                                @endforelse#}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/whomiliked.html
{% extends 'layouts/app.html' %}

{% block content %}
    {% load static %}
    {% load is_liked_by_me %}

    <div class="text-center mt-3">
        <h2>{{ likes.count }} people liked you</h2>
    </div>

    <div class="container mt-3">

        <div class="row">
            {% for like in likes %}
                <div class="col-sm-6 col-md-4 col-lg-4 col-xl-2">
                    <div class="card mb-4">
                        <div class="card-img-wrapper">
                            <img class="card-img-top img-thumbnail" src="{% static 'images/user.png' %}" alt="">
                            <ul class="list-inline member-icons animate text-center">
                                <li class="list-inline-item">
                                    <a href="{% url 'app:member_detail' like.member.id %}" class="btn btn-primary"
                                       title="Show profile">
                                        <i style="color: #fff;" class="fa fa-user"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <button class="btn btn-primary" title="Send Message">
                                        <i class="fa fa-envelope"></i>
                                    </button>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body p-1">
                            <h6 class="card-title text-center mb-1"><i class="fa fa-user"></i>
                                {{ like.member.username }}
                            </h6>
                            <p class="card-text text-muted text-center">Age:
                                <small>{{ like.member.age }}</small>
                            </p>
                            <p class="card-text text-muted text-center">Dhaka</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="d-flex justify-content-center">

    </div>

{% endblock %}